site_name: Rarible Protocol
site_description: Rarible Protocol documentation

nav:
  - 'Rarible Protocol Overview': 'index.md'
  - 'Overview':
      - 'Reasons for using protocol': 'overview/reasons.md'
      - 'API Reference': 'overview/api-reference.md'
      - 'SDK': 'overview/union-sdk.md'
      - 'Resources': 'overview/resources.md'
      - 'Glossary': 'overview/glossary.md'
  - 'Getting Started':
      - 'Protocol Example': 'getting-started/protocol-example.md'
  - 'Use Cases':
      - 'Picnic': 'use-cases/picnic.md'
      - 'cocoNFT': 'use-cases/coconft.md'
      - 'MintGate': 'use-cases/mintgate.md'
      - 'EZCode SDK plugin': 'use-cases/bubblesdk.md'
      - 'Setting Up Royalties on an External Collection': 'use-cases/royalties-on-a-external-collection.md'
  - 'Ethereum':
      - 'Ethereum Overview': 'ethereum/ethereum-overview.md'
      - 'Contract Addresses': 'ethereum/contract-addresses.md'
      - 'Smart Contracts':
          - 'Smart Contracts Overview': 'ethereum/smart-contracts/smart-contracts.md'
          - 'ExchangeV2':
              - 'ExchangeV2 Overview': 'ethereum/smart-contracts/exchangev2-overview.md'
              - 'ExchangeV2 Matching Orders': 'ethereum/smart-contracts/exchangev2-matching-orders.md'
              - 'ExchangeV2 Sell and Bid': 'ethereum/smart-contracts/exchangev2-sell-bid.md'
              - 'ExchangeV2 Update and Cancel': 'ethereum/smart-contracts/exchangev2-update-cancel.md'
          - 'Tokens': 'ethereum/smart-contracts/tokens.md'
          - 'Fees': 'ethereum/smart-contracts/fees.md'
          - 'Royalties': 'ethereum/smart-contracts/royalties.md'
      - 'Ethereum SDK': 'ethereum/sdk/ethereum-sdk.md'
      - 'Assets':
          - 'Creating': 'ethereum/assets/creating-an-asset.md'
          - 'Token Factories': 'ethereum/assets/token-factories.md'
          - 'Royalties Schema': 'ethereum/assets/royalties.md'
          - 'Asset Discovery': 'ethereum/assets/asset-discovery.md'
      - 'Exchange':
          - 'Exchange Overview': 'ethereum/exchange/exchange-overview.md'
          - 'Creating A Sell Order': 'ethereum/exchange/creating-a-sell-order.md'
          - 'Order Discovery': 'ethereum/exchange/order-discovery.md'
          - 'Accepting a Buy Order': 'ethereum/exchange/accepting-a-buy-order.md'
          - 'Updating/Canceling an Order': 'ethereum/exchange/updating-cancelling-an-order.md'
          - 'Contract Wallets': 'ethereum/exchange/contract-wallets.md'


theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - search.highlight
    - navigation.instant

plugins:
  - search
repo_url: https://github.com/rarible/protocol
repo_name: rarible/protocol

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/3ByePUMAvB

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - tables
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.snippets
